xname: gsheet.action test
on:
  pull_request:
    types: [opened, deleted, closed, reopened]

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - id: 'update_worksheet'
        uses: jroehl/gsheet.action@v2.0.0 # you can specify '@release' to always have the latest changes
        with:
          spreadsheetId: 1aIAwzMgDdXQUr2A_A_sC3ShEjQky-gYEzqB1TbPzdjA
          commands: | # list of commands, specified as a valid JSON string
            [
              { "command": "updateData", "args": { "worksheetTitle": "GitHub Issues Tracker", "data": [[github.event.pull_request]] }}
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
      - name: dump results
        env:
          #  the output of the action can be found in ${{ steps.update_worksheet.outputs.results }}
          RESULTS: ${{ steps.update_worksheet.outputs.results }}
        run: echo "$RESULTS" | jq
